### PR TITLE
Block deserialization.

### PR DESCRIPTION
**Pull request by longfin**
This PR adds `Block<>.FromBencoded()` to deserialize from bytes that have encoded bencodex. it's useful when implementing P2P Block exchange.

### CODE REVIEW

**Comment by dahlia** [comment]
Note that a build error during pushing docs was fixed by PR #45.  You should rebase this PR on the current master again (20386c5f95383b8ae6b4fc378d6f4c2a6e496148 at least).

**Comment by longfin** [comment]
Rebased.

**Comment by longfin** [comment]
Rebased because #43 was merged.

**Comment by longfin** [comment]
Rebased because #47 was merged.

**Comment by longfin** [comment]
> Though it's off-topic, I find names like `FromBencodex()`/`ToBencodex()` slightly more consistent than `FromBencoded()`/`Bencode()` for style.

I'll clean up in next PR.

**Pull request merged**
